workers:
    sass:
        cmd: ['symfony', 'console', 'sass:build', '--watch']
    tailwind:
        depends_on:
            - sass
        cmd: ['symfony', 'console', 'tailwind:build', '--watch']
    messenger_consume_async:
        cmd: ['symfony', 'console', 'messenger:consume', 'async_priority_main', 'async_priority_high', 'async_priority_medium', 'async_priority_low', 'async', '--no-debug']